### ISSUE TITLE
Respect baseUri for static Targets

### ISSUE THREAD

**Issue by paavo** [flownative/flow-google-cloudstorage#36]
it looks like baseUri is ignored when using a GcsTarget as static target @kdambekalns 

```
Neos:
  Flow:
    resource:
      targets:
        googleStaticResourcesTarget:
          target: 'Flownative\Google\CloudStorage\GcsTarget'
          targetOptions:
            bucket: '%env:CLOUDSTORAGE_S3_BUCKET%'
            keyPrefix: 'statictarget/'
            baseUri: '%env:CLOUDSTORAGE_S3_PUBLICURL%'
            
```

```
Neos:
  Flow:
    resource:
      collections:
        static:
          target: 'googleStaticResourcesTarget'
```
